develop19

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,10 +53,18 @@ jobs:
           flutter-version: '3.27.4'
       - name: Install dependencies
         run: flutter pub get
+      - name: Clean Flutter project
+        run: flutter clean
       - name: Build Android APK
         run: flutter build apk --release
       - name: Build Android AAB
         run: flutter build appbundle --release
+      - name: Check if APK exists
+        run: |
+          if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "APK file not found!"
+            exit 1
+          fi
       - name: Upload Android APK artifact
         uses: actions/upload-artifact@v4
         with:
@@ -67,8 +75,6 @@ jobs:
         with:
           name: android-aab
           path: build/app/outputs/bundle/release/app-release.aab
-
-
 
   deploy:
     needs: build-android
